#!/usr/bin/env python3
# =============================================================================
# geometry_split.py -- DERIVE the gate/report split for the OBJ-D latency bars.
# Task U14. Reads out/geo_*.txt, writes out/geometry.md.
#
# THE QUESTION IT ANSWERS
# -----------------------------------------------------------------------------
# U33 measured that this rig's stall geometry is HAND-PLACED, that seeds vary
# jitter and not phase, and that even PAIRED quantities move about 0.9 pt when
# the phase is rotated -- so "24 seeds" is 24 jitter samples of ONE geometry, not
# a confidence interval (ROADMAP, "U33 -- the corrected phase result"). It drew
# the consequence for the U8 gate but nobody had applied it to a NEW gate.
#
# Applied here as the rule that decides what may be gated at all:
#
#     A bar is GATED only if its verdict is IDENTICAL across the geometry
#     sample. A bar whose verdict flips is REPORTED, never gated -- gating it
#     would be gating the stall phase, which is invented.
#
# This is a threshold DERIVED FROM MEASUREMENT, which is the only kind this
# project allows. It is also conservative in the right direction: sampling a
# subset of rotations can only SHRINK measured geometry spread (U33), so a bar
# that flips here would flip at least as often over the full rotation family.
#
# The sample is canonical + four `rig_checks.phase_drops` rotations. That is a
# SMALL sample and it is named as such: four rotations do not establish that a
# surviving bar is stable, only that it did not flip on four draws. Widening it
# is one more run of the loop in out/RUNME.sh.
#
# Run:  python geometry_split.py           (after out/RUNME.sh)
# =============================================================================
import glob
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'out')
CHECK = re.compile(r'^\s{2}(SPD-\d[a-z]|HOLD-\d[a-z])\s+(.*?)\s+(PASS|FAIL)\s')


def read(path):
    v = {}
    for line in open(path, encoding='utf-8', errors='replace'):
        m = CHECK.match(line)
        if m:
            v[(m.group(1), ' '.join(m.group(2).split()))] = m.group(3)
    return v


def main():
    files = sorted(glob.glob(os.path.join(OUT, 'geo_*.txt')))
    if not files:
        raise SystemExit('no out/geo_*.txt -- run out/RUNME.sh first')
    geos = {}
    for f in files:
        g = os.path.basename(f)[4:-4]
        geos[g] = read(f)
    names = sorted(geos, key=lambda x: (x != 'canonical', x))
    keys = sorted(set().union(*[set(v) for v in geos.values()]))

    rows = []
    for k in keys:
        verds = [geos[g].get(k, '-') for g in names]
        stable = len(set(verds)) == 1 and '-' not in verds
        rows.append((k, verds, stable))

    by_id = {}
    for (bid, subj), verds, stable in rows:
        by_id.setdefault(bid, []).append(stable)
    gated = sorted(b for b, ss in by_id.items() if all(ss))
    reported = sorted(b for b, ss in by_id.items() if not all(ss))

    lines = []
    lines.append('# Geometry study -- which OBJ-D latency bars may be gated (U14)')
    lines.append('')
    lines.append('GENERATED by `geometry_split.py` from `out/geo_*.txt`. Do not hand-edit.')
    lines.append('')
    lines.append('Geometries scored: ' + ', '.join(names) +
                 '  (integers = `rig_checks.phase_drops(name, GEO, T)`, U33\'s corrected')
    lines.append('count- and duration-preserving rotation; no interval over t=0).')
    lines.append('Seeds, offers, rigs, hold policy and bar arithmetic identical in all runs;')
    lines.append('the ONLY thing that varies is the stall phase of the spotty archetypes.')
    lines.append('')
    lines.append('| bar | subject | ' + ' | '.join(names) + ' | geometry-stable |')
    lines.append('|---|---|' + '---|' * (len(names) + 1))
    for (bid, subj), verds, stable in rows:
        lines.append('| `%s` | %s | %s | %s |'
                     % (bid, subj, ' | '.join(verds), 'YES' if stable else '**NO**'))
    lines.append('')
    lines.append('## Result')
    lines.append('')
    lines.append('```python')
    lines.append('GATED = (' + ', '.join("'%s'" % b for b in gated) + ')')
    lines.append('REPORTED = (' + ', '.join("'%s'" % b for b in reported) + ')')
    lines.append('```')
    lines.append('')
    lines.append('A bar id is GATED only when EVERY one of its checks kept the same verdict')
    lines.append('on every geometry. One flip anywhere in the id demotes the whole id: the')
    lines.append('gate classifies by id, so a mixed id would gate a coin flip under another')
    lines.append('check\'s name.')
    lines.append('')
    lines.append('**Named non-coverage.** %d rotations is a small sample. It does not show a'
                 % (len(names) - 1))
    lines.append('surviving bar is stable -- only that it did not flip on these draws. U33\'s')
    lines.append('own conclusion applies unchanged: the geometry axis is sampled by PHASE')
    lines.append('ONLY; stall COUNT and DURATION remain the hand-placed canonical values, so')
    lines.append('this is a lower bound on the true spread.')
    open(os.path.join(OUT, 'geometry.md'), 'w', encoding='utf-8', newline='\n').write(
        '\n'.join(lines) + '\n')
    print('\n'.join(lines[-12:]))
    print('\nwrote out/geometry.md  (%d checks, %d geometries)' % (len(rows), len(names)))


if __name__ == '__main__':
    main()
